version: "3.8"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack-ses
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ses
      - AWS_ACCESS_KEY_ID=temp-key-id
      - AWS_SECRET_ACCESS_KEY=temp-access-key
      - DEFAULT_REGION=ap-northeast-2
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
